# Generated by Django 5.1 on 2024-08-27 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_data',
        ),
    ]
