# Generated by Django 5.1 on 2024-09-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_test_creator_customuser_createquiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createquiz',
            name='is_correct',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
