# Generated by Django 5.1 on 2024-10-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_alter_createquiz_is_correct_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=255)),
                ('Introduction', models.CharField(max_length=255)),
            ],
        ),
    ]
