# Generated by Django 5.1 on 2024-10-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_abouttest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutTest',
        ),
    ]
