# Generated by Django 5.1 on 2024-10-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_createquiz_question_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateQuiz',
        ),
    ]
