# Generated by Django 5.1 on 2024-10-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_createquiz_question_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.DeleteModel(
            name='CreateQuiz',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
