# Generated by Django 5.1 on 2024-10-08 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_createtest_question_option'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateQuiz',
            fields=[
                ('question_ID', models.AutoField(primary_key=True, serialize=False)),
                ('test_title', models.CharField(max_length=255)),
                ('Introduction', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('question_type', models.CharField(max_length=255)),
                ('options', models.JSONField(default=list)),
                ('is_correct', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
