# Generated by Django 5.1 on 2024-10-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_createquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.DeleteModel(
            name='CreateTest',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
